version: "3.8"

services:
  wordpress:
    build: ./
    container_name: wp-container
    ports:
      - "8000:80"
    volumes:
      - ./wp/app/public:/var/www/html
      - ./wp-initial.sh:/tmp/wp-initial.sh
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    depends_on:
      - mysql
    restart: always
    tty: true

  mysql:
    image: mysql:5.7
    container_name: db-container
    ports:
      - "3306:3306"
    volumes:
      - db_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    tty: true

volumes:
  db_mysql: