version: "3.8"

services:
  wordpress:
    build:
      context: .
      dockerfile: .docker/wordpress/Dockerfile
    ports:
      - 127.0.0.1:${WP_PORT}:80
    volumes:
      - ./wp/app/public:/var/www/html
      - ./wp-initial.sh:/tmp/wp-initial.sh
    environment:
      - WORDPRESS_DB_HOST=${MYSQL_HOST}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql
    restart: always
    tty: true

  mysql:
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Tokyo
    restart: always
    tty: true

volumes:
  db_mysql: